### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shjee-afridi** [sentrionic/Valkyrie#21]
`
    2022-06-23T16:00:32.417976+00:00 app[web.1]: panic: runtime error: invalid memory address or nil pointer dereference
    2022-06-23T16:00:32.417986+00:00 app[web.1]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf7fca4]
    2022-06-23T16:00:32.417986+00:00 app[web.1]: 
    2022-06-23T16:00:32.417988+00:00 app[web.1]: goroutine 1 [running]:
    2022-06-23T16:00:32.418020+00:00 app[web.1]: main.inject(0xc00051eb10)
    2022-06-23T16:00:32.418047+00:00 app[web.1]: 	/tmp/build_3dbb8172/injection.go:99 +0xc64
    2022-06-23T16:00:32.418053+00:00 app[web.1]: main.main()
    2022-06-23T16:00:32.418080+00:00 app[web.1]: 	/tmp/build_3dbb8172/main.go:42 +0x125
`
This error in logs when trying to run my server in heroku.
Im using redis labs to cloud host my redis: https://app.redislabs.com/#/login

**Comment by sentrionic** [comment]
That error is not very helpful.

If it helps my `REDIS_URL` config var is set to `rediss://:password@host:port`.

**Comment by BlackReaper33** [comment]
I tried your scheme too not working...
Here is my URL: `redis://username:password@redis-19318.c302.asia-northeast1-1.gce.cloud.redislabs.com:19318`

Please help which redis service are you using?

**Comment by sentrionic** [comment]
The Heroku one.

**Comment by BlackReaper33** [comment]
What do you suggest i do now-?....

**Comment by sentrionic** [comment]
Learn Go and debug the error.

**Comment by BlackReaper33** [comment]
.
